import type { RuntimeMode } from '../runtime/runtime-mode.ts';

/**
 * Audit entry domain types (schema v1). Mirrors architecture.md §"Audit Entry
 * JSON Schema (v1)". The runtime validator + JSON Schema export live in
 * `../schemas/audit-entry-schema.ts`.
 */

export const AUDIT_SCHEMA_VERSION = 1 as const;
export type AuditSchemaVersion = typeof AUDIT_SCHEMA_VERSION;

/** Agent invocation scope — shared with Epic 11 agent scopes. */
export const AUDIT_SCOPES = ['inline', 'page', 'workspace'] as const;
export type AuditScope = (typeof AUDIT_SCOPES)[number];

export const AUDIT_OPERATIONS = ['create', 'update', 'delete', 'rollback', 'structural'] as const;
export type AuditOperation = (typeof AUDIT_OPERATIONS)[number];

/** Write-ahead lifecycle status. */
export const AUDIT_STATUSES = ['pending', 'committed', 'rejected'] as const;
export type AuditStatus = (typeof AUDIT_STATUSES)[number];

export const AUDIT_ACTOR_KINDS = ['agent', 'human', 'system'] as const;
export type AuditActorKind = (typeof AUDIT_ACTOR_KINDS)[number];

export const AUDIT_RESOURCE_KINDS = ['block', 'page', 'navigation', 'project-config'] as const;
export type AuditResourceKind = (typeof AUDIT_RESOURCE_KINDS)[number];

export type AuditActor = {
  kind: AuditActorKind;
  /** Provider port identifier; empty/absent when kind != 'agent'. */
  agentProvider?: string;
};

export type AuditTarget = {
  resourceKind: AuditResourceKind;
  pageId?: string;
  blockId?: string;
  navigationId?: string;
};

export type AuditDiff = {
  /** Pre-change snapshot (canonical doc-content-v1 fragment or config object). */
  before?: unknown;
  /** Post-change snapshot. */
  after?: unknown;
  summary?: string;
};

export type AuditEntry = {
  schemaVersion: AuditSchemaVersion;
  /** ULID for ordered uniqueness (generated by the repository, Story 10.2). */
  id: string;
  /** ISO 8601 timestamp. */
  timestamp: string;
  scope: AuditScope;
  operation: AuditOperation;
  status: AuditStatus;
  projectId: string;
  target: AuditTarget;
  actor: AuditActor;
  runtimeMode: RuntimeMode;
  diff?: AuditDiff;
  /** Populated only when status = 'rejected'. */
  rejectionReason?: string;
  /** If operation = 'rollback', references the original entry id. */
  rollbackOf?: string;
  /** SHA-256 of the triggering prompt; PII-safe. */
  promptDigest?: string;
};

export function isAuditScope(value: unknown): value is AuditScope {
  return typeof value === 'string' && (AUDIT_SCOPES as readonly string[]).includes(value);
}

export function isAuditOperation(value: unknown): value is AuditOperation {
  return typeof value === 'string' && (AUDIT_OPERATIONS as readonly string[]).includes(value);
}

export function isAuditStatus(value: unknown): value is AuditStatus {
  return typeof value === 'string' && (AUDIT_STATUSES as readonly string[]).includes(value);
}

export function isAuditActorKind(value: unknown): value is AuditActorKind {
  return typeof value === 'string' && (AUDIT_ACTOR_KINDS as readonly string[]).includes(value);
}

export function isAuditResourceKind(value: unknown): value is AuditResourceKind {
  return typeof value === 'string' && (AUDIT_RESOURCE_KINDS as readonly string[]).includes(value);
}
